### ISSUE TITLE
Clicking 0 Threshold Item

### ISSUE THREAD

**Issue by pgrepsfeldt** [Pouka-dev/re_storage_energistics#7]
When clicking on an item with a 0 threshold in the Network Requester Chest the following error occurs:
(Note: this occurs once you have initially setup the 0 request item, closed the UI, and the reopened and click the item again)

The mod RE:Storage Energistics (1.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event re_storage_energistics::on_gui_click (ID 1)
..._storage_energistics__/cores/guis/interface-node-gui.lua:109: attempt to compare nil with number
stack traceback:
	..._storage_energistics__/cores/guis/interface-node-gui.lua:109: in function 'SetAmountText'
	..._storage_energistics__/cores/guis/interface-node-gui.lua:162: in function 'SetSelectedIndex'
	..._storage_energistics__/cores/guis/interface-node-gui.lua:335: in function '?'
	__re_storage_energistics__/cores/guis/gui-manager.lua:164: in function 'HandlerGeneralizedGuiEvent'
	__re_storage_energistics__/cores/guis/gui-manager.lua:210: in function <__re_storage_energistics__/cores/guis/gui-manager.lua:209>

**Comment by pgrepsfeldt** [comment]
Steps to reproduce crash:
When a filter has 0 amount entered
The window is closed
Chest selected and window reopened
0 amount item left-clicked (nil error)

interface-node-gui.lua
Line 162:  SetAmountText(guiData, (filterAmount >= 0 and tostring(filterAmount)) or "")
Line 163:  SetAmountMinForCallText(guiData, (filterAmountMinForCall >= 0 and tostring(filterAmountMinForCall)) or "")

This fixes that issue. Possibly need to change blank string to default to "0" as well

**Comment by Pouka-dev** [comment]
Ok, thanks for this issue. I'm patch this soon.
